from __future__ import annotations

import argparse
import asyncio

from pydantic import BaseModel

from ds_workspace_mcp.aggregation import AggregationResult
from ds_workspace_mcp.cli import build_parser
from ds_workspace_mcp.config import Settings
from ds_workspace_mcp.core import DatasetIssue, DatasetPreview
from ds_workspace_mcp.datasets import DatasetColumnMetadata, DatasetMetadata
from ds_workspace_mcp.diagnostics import CorrelationSummary, LeakageSummary, LeakageWarning
from ds_workspace_mcp.drift import (
    CardinalityChange,
    CategoricalDrift,
    CategoryDistributionChange,
    ColumnTypeChange,
    DatasetComparisonResult,
    DatasetComparisonSampling,
    DatasetDriftDiagnostics,
    DatasetSchemaDiff,
    NullRateChange,
    NumericDrift,
    RowCountChange,
    TimestampRangeChange,
)
from ds_workspace_mcp.experiment_plan import ExperimentPlanResult
from ds_workspace_mcp.feature_selection import FeatureSelectionResult
from ds_workspace_mcp.ml.baselines import (
    BaselineEvaluationResult,
    ClassificationMetrics,
    ValidationSplitMetadata,
)
from ds_workspace_mcp.modeling_readiness import ModelingReadinessResult
from ds_workspace_mcp.modeling_report import ModelingReportResult
from ds_workspace_mcp.overview import DatasetOverview
from ds_workspace_mcp.profiling import (
    BooleanColumnProfile,
    CandidateKeyProfile,
    CategoricalColumnProfile,
    ColumnQualitySignal,
    DatasetProfile,
    DatasetQualityDiagnostics,
    DatetimeColumnProfile,
    NumericColumnProfile,
    NumericHistogramBin,
    ProfileHeuristicSignal,
    ProfilingLimits,
    ValueFrequency,
)
from ds_workspace_mcp.report_export import (
    ComparedModelingReport,
    ComparedModelingReportSection,
    CopiedModelingReport,
    DeletedModelingReport,
    ModelingReportCatalogSummary,
    ModelingReportMetadata,
    ModelingReportSection,
    ModelingReportSectionMatch,
    ModelingReportSectionSummary,
    PreviewModelingReport,
    ReadModelingReport,
    ReadModelingReportSection,
    RenamedModelingReport,
    ReportSearchMatch,
    SavedModelingReport,
    SavedModelingReportSection,
    StoredModelingReport,
)
from ds_workspace_mcp.server import create_mcp_server
from ds_workspace_mcp.sql.duckdb_engine import DuckDBQueryResult
from ds_workspace_mcp.sql.sqlite_engine import (
    SQLiteColumnInfo,
    SQLiteDatabaseInfo,
    SQLiteQueryResult,
    SQLiteTableSchema,
)
from ds_workspace_mcp.targeting import TargetSuggestionResult
from ds_workspace_mcp.timeseries import (
    FrequencyInferenceResult,
    GroupTimeSeriesSummary,
    TimeSeriesValidationResult,
)

EXPECTED_RESOURCE_URIS = [
    "databases://sqlite",
    "datasets://catalog",
    "datasets://catalog/all",
    "reports://modeling",
    "reports://modeling/latest",
    "reports://modeling/latest/sections",
    "reports://modeling/latest/sections/{section_heading}",
    "reports://modeling/{output_name}",
    "reports://modeling/{output_name}/sections",
    "reports://modeling/{output_name}/sections/{section_heading}",
]

EXPECTED_TOOL_NAMES = [
    "aggregate_dataset_tool",
    "assess_modeling_readiness",
    "build_experiment_plan",
    "build_modeling_report",
    "compare_datasets",
    "compare_latest_modeling_report_sections_tool",
    "compare_latest_modeling_reports_tool",
    "compare_modeling_report_sections",
    "compare_modeling_reports",
    "copy_latest_modeling_report_tool",
    "copy_modeling_report",
    "delete_modeling_report",
    "describe_sqlite_table",
    "detect_csv_issues",
    "detect_possible_target_leakage",
    "evaluate_baseline_model",
    "inspect_dataset_file",
    "inspect_latest_modeling_report_tool",
    "inspect_modeling_report",
    "list_excel_sheets_tool",
    "list_latest_modeling_report_sections_tool",
    "list_modeling_report_sections",
    "list_modeling_reports",
    "list_recent_modeling_reports_tool",
    "list_sqlite_databases_tool",
    "list_sqlite_tables",
    "preview_csv",
    "preview_dataset_file",
    "preview_latest_modeling_report_tool",
    "preview_modeling_report",
    "profile_csv",
    "profile_dataset_file",
    "query_csv_with_duckdb",
    "query_dataset_with_duckdb",
    "query_sqlite",
    "read_latest_modeling_report_section_tool",
    "read_latest_modeling_report_tool",
    "read_modeling_report",
    "read_modeling_report_section",
    "rename_latest_modeling_report_tool",
    "rename_modeling_report",
    "save_latest_modeling_report_section_tool",
    "save_modeling_report",
    "save_modeling_report_section_tool",
    "search_latest_modeling_report_content_tool",
    "search_latest_modeling_report_sections_tool",
    "search_modeling_report_content",
    "search_modeling_report_sections",
    "search_modeling_reports",
    "suggest_feature_columns",
    "suggest_target_columns",
    "summarize_correlations",
    "summarize_dataset",
    "summarize_modeling_report_catalog_tool",
    "summarize_modeling_report_sections",
    "validate_time_series_dataset_tool",
]

EXPECTED_PROMPT_NAMES = [
    "dataset_analysis_prompt",
    "modeling_report_review_prompt",
]

EXPECTED_CLI_COMMANDS = [
    "compare-datasets",
    "compare-latest-modeling-report-sections",
    "compare-latest-modeling-reports",
    "compare-modeling-report-sections",
    "compare-modeling-reports",
    "copy-latest-modeling-report",
    "copy-modeling-report",
    "delete-modeling-report",
    "generate-sample-healthcare-data",
    "inspect-latest-modeling-report",
    "inspect-modeling-report",
    "list-datasets",
    "list-latest-modeling-report-sections",
    "list-modeling-report-sections",
    "list-modeling-reports",
    "list-recent-modeling-reports",
    "plan-modeling",
    "preview-latest-modeling-report",
    "preview-modeling-report",
    "profile-dataset",
    "read-latest-modeling-report",
    "read-latest-modeling-report-section",
    "read-modeling-report",
    "read-modeling-report-section",
    "rename-latest-modeling-report",
    "rename-modeling-report",
    "report-modeling",
    "save-latest-modeling-report-section",
    "save-modeling-report",
    "save-modeling-report-section",
    "search-latest-modeling-report-content",
    "search-latest-modeling-report-sections",
    "search-modeling-report-content",
    "search-modeling-report-sections",
    "search-modeling-reports",
    "serve",
    "summarize-modeling-report-sections",
    "summarize-modeling-reports",
]

EXPECTED_RESULT_MODEL_FIELDS = {
    "BaselineEvaluationResult": [
        "file_name",
        "target_column",
        "task_type",
        "train_rows",
        "test_rows",
        "regression_metrics",
        "classification_metrics",
        "class_counts",
        "train_class_counts",
        "test_class_counts",
        "validation",
    ],
    "BooleanColumnProfile": ["column", "true_count", "false_count", "missing_count"],
    "CandidateKeyProfile": [
        "columns",
        "uniqueness_ratio",
        "missing_count",
        "reason",
        "confidence",
    ],
    "CategoricalColumnProfile": [
        "column",
        "count",
        "unique_count",
        "top_value",
        "top_value_frequency",
        "top_values",
        "rare_category_count",
        "rare_category_mass",
        "entropy",
        "normalized_entropy",
        "quality_signals",
    ],
    "ClassificationMetrics": ["accuracy", "balanced_accuracy", "macro_f1", "weighted_f1"],
    "AggregationResult": [
        "file_name",
        "group_by",
        "metric_columns",
        "rows",
        "row_count",
        "total_group_count",
        "limit_applied",
    ],
    "CardinalityChange": ["column", "left_unique_count", "right_unique_count", "change"],
    "CategoricalDrift": [
        "column",
        "left_count",
        "right_count",
        "left_unique_count",
        "right_unique_count",
        "total_variation_distance",
        "jensen_shannon_divergence",
        "compared_categories",
        "other_category_included",
        "effect_size",
        "statistical_evidence",
    ],
    "CategoryDistributionChange": [
        "category",
        "left_proportion",
        "right_proportion",
        "difference",
    ],
    "ColumnTypeChange": ["column", "left_dtype", "right_dtype"],
    "ColumnQualitySignal": ["column", "signal", "reason", "severity", "confidence"],
    "ComparedModelingReport": [
        "output_name",
        "other_output_name",
        "changed",
        "added_line_count",
        "removed_line_count",
        "diff_preview",
    ],
    "ComparedModelingReportSection": [
        "output_name",
        "other_output_name",
        "section_heading",
        "changed",
        "added_line_count",
        "removed_line_count",
        "diff_preview",
    ],
    "CopiedModelingReport": [
        "source_output_name",
        "new_output_name",
        "source_output_path",
        "new_output_path",
    ],
    "CorrelationSummary": ["file_name", "method", "numeric_columns", "top_correlations"],
    "DatasetIssue": ["column", "issue_type", "description"],
    "DatasetComparisonResult": [
        "left_file_name",
        "right_file_name",
        "schema_diff",
        "drift",
        "sampling",
    ],
    "DatasetComparisonSampling": [
        "strategy",
        "max_rows_per_dataset",
        "left_rows_analyzed",
        "right_rows_analyzed",
        "left_truncated",
        "right_truncated",
        "note",
    ],
    "DatasetColumnMetadata": ["name", "data_type"],
    "DatasetDriftDiagnostics": ["numeric", "categorical", "timestamp_ranges"],
    "DatasetMetadata": [
        "file_name",
        "format",
        "size_bytes",
        "modified_time_ns",
        "fingerprint",
        "can_query",
        "row_count",
        "column_count",
        "columns",
        "format_metadata",
    ],
    "DatasetOverview": [
        "file_name",
        "row_count",
        "column_count",
        "sample_columns",
        "numeric_column_count",
        "categorical_column_count",
        "boolean_column_count",
        "datetime_column_count",
        "columns_with_missing_values",
        "high_missingness_columns",
        "possible_identifier_columns",
        "top_correlations",
        "recommended_next_tools",
        "summary",
    ],
    "DatasetPreview": ["file_name", "rows"],
    "DatasetProfile": [
        "file_name",
        "row_count",
        "column_count",
        "columns",
        "dtypes",
        "missing_values",
        "missing_percentage",
        "numeric_columns",
        "categorical_columns",
        "boolean_columns",
        "datetime_columns",
        "data_quality",
        "profiling_limits",
    ],
    "DatasetQualityDiagnostics": [
        "duplicate_row_count",
        "duplicate_row_percentage",
        "candidate_keys",
        "empty_columns",
        "one_value_columns",
        "probable_free_text_columns",
        "possible_identifier_columns",
    ],
    "DatasetSchemaDiff": [
        "added_columns",
        "removed_columns",
        "dtype_changes",
        "null_rate_changes",
        "row_count",
        "cardinality_changes",
    ],
    "DeletedModelingReport": ["output_name", "output_path"],
    "DatetimeColumnProfile": ["column", "count", "min", "max"],
    "DuckDBQueryResult": ["file_name", "columns", "rows", "row_count", "limit_applied"],
    "ExperimentPlanResult": [
        "file_name",
        "target_column",
        "target_source",
        "suggested_task_type",
        "validation_strategy",
        "recommended_validation_strategy",
        "recommended_time_column",
        "recommended_group_column",
        "feature_columns",
        "review_columns",
        "risks",
        "baseline_models",
        "evaluation_metrics",
        "next_steps",
        "summary",
    ],
    "FeatureSelectionResult": [
        "file_name",
        "target_column",
        "include_columns",
        "review_columns",
        "exclude_columns",
        "suggestions",
        "summary",
    ],
    "FrequencyInferenceResult": [
        "frequency",
        "frequency_kind",
        "confidence",
        "support_ratio",
        "candidate_interval",
        "is_regular",
        "is_irregular",
        "missing_interval_count",
    ],
    "GroupTimeSeriesSummary": [
        "group",
        "row_count",
        "duplicate_timestamps",
        "missing_intervals",
        "inferred_frequency",
        "frequency",
    ],
    "LeakageSummary": ["file_name", "target_column", "warnings"],
    "LeakageWarning": ["column", "warning_type", "description", "severity", "confidence"],
    "ModelingReadinessResult": [
        "file_name",
        "target_column",
        "target_source",
        "suggested_task_type",
        "validation_strategy",
        "recommended_validation_strategy",
        "recommended_time_column",
        "recommended_group_column",
        "target_candidate",
        "target_suggestions",
        "feature_selection",
        "leakage_warnings",
        "recommended_next_tools",
        "summary",
    ],
    "ModelingReportCatalogSummary": [
        "report_count",
        "total_size_bytes",
        "most_recent_reports",
    ],
    "ModelingReportMetadata": [
        "output_name",
        "output_path",
        "size_bytes",
        "created_at",
        "metadata_changed_at",
        "modified_at",
        "content_sha256",
    ],
    "ModelingReportResult": ["file_name", "target_column", "headline", "markdown"],
    "ModelingReportSection": ["heading", "level"],
    "ModelingReportSectionMatch": [
        "output_name",
        "output_path",
        "heading",
        "level",
        "snippet",
    ],
    "ModelingReportSectionSummary": [
        "heading",
        "level",
        "report_count",
        "example_reports",
    ],
    "NullRateChange": ["column", "left_null_rate", "right_null_rate", "change"],
    "NumericColumnProfile": [
        "column",
        "count",
        "mean",
        "std",
        "min",
        "q25",
        "median",
        "q75",
        "max",
        "iqr",
        "robust_spread",
        "histogram",
        "iqr_outlier_count",
        "z_score_outlier_count",
        "skewness",
        "quality_signals",
    ],
    "NumericDrift": [
        "column",
        "left_count",
        "right_count",
        "left_mean",
        "right_mean",
        "standardized_mean_difference",
        "left_std",
        "right_std",
        "median_shift",
        "q25_shift",
        "q75_shift",
        "ks_statistic",
        "effect_size",
        "statistical_evidence",
    ],
    "NumericHistogramBin": ["lower_bound", "upper_bound", "count"],
    "PreviewModelingReport": [
        "output_name",
        "output_path",
        "headline",
        "preview_markdown",
        "line_count",
    ],
    "ReadModelingReport": ["output_name", "output_path", "markdown"],
    "ReadModelingReportSection": [
        "output_name",
        "output_path",
        "heading",
        "level",
        "markdown",
    ],
    "RenamedModelingReport": [
        "old_output_name",
        "new_output_name",
        "old_output_path",
        "new_output_path",
    ],
    "ReportSearchMatch": ["output_name", "output_path", "headline", "snippet"],
    "ProfileHeuristicSignal": ["signal", "reason", "severity", "confidence"],
    "ProfilingLimits": [
        "max_categorical_values",
        "max_histogram_bins",
        "max_candidate_key_columns",
        "max_candidate_key_combinations",
    ],
    "RowCountChange": ["left_row_count", "right_row_count", "change", "exact"],
    "SavedModelingReport": ["file_name", "target_column", "output_path", "headline"],
    "SavedModelingReportSection": [
        "source_output_name",
        "section_heading",
        "output_path",
    ],
    "SQLiteColumnInfo": [
        "cid",
        "name",
        "data_type",
        "not_null",
        "default_value",
        "is_primary_key",
    ],
    "SQLiteDatabaseInfo": ["file_name"],
    "SQLiteQueryResult": ["file_name", "columns", "rows", "row_count", "limit_applied"],
    "SQLiteTableSchema": ["file_name", "table_name", "columns"],
    "StoredModelingReport": [
        "output_name",
        "output_path",
        "size_bytes",
        "created_at",
        "modified_at",
        "content_sha256",
    ],
    "TargetSuggestionResult": ["file_name", "candidates", "summary"],
    "TimestampRangeChange": [
        "column",
        "left_min",
        "left_max",
        "right_min",
        "right_max",
        "min_shift_seconds",
        "max_shift_seconds",
    ],
    "TimeSeriesValidationResult": [
        "file_name",
        "time_column",
        "target_column",
        "group_column",
        "row_count",
        "parsed_timestamp_count",
        "duplicate_timestamps",
        "is_sorted",
        "inferred_frequency",
        "missing_intervals",
        "frequency",
        "missing_target_values",
        "group_summaries",
        "warnings",
    ],
    "ValueFrequency": ["value", "count"],
    "ValidationSplitMetadata": [
        "strategy",
        "test_size",
        "random_state",
        "shuffle",
        "stratified",
        "time_column",
        "group_column",
        "train_start_time",
        "train_end_time",
        "test_start_time",
        "test_end_time",
        "train_group_count",
        "test_group_count",
        "group_overlap",
    ],
}

RESULT_MODELS: list[type[BaseModel]] = [
    BaselineEvaluationResult,
    AggregationResult,
    BooleanColumnProfile,
    CandidateKeyProfile,
    CardinalityChange,
    CategoricalDrift,
    CategoricalColumnProfile,
    CategoryDistributionChange,
    ClassificationMetrics,
    ColumnQualitySignal,
    ColumnTypeChange,
    ComparedModelingReport,
    ComparedModelingReportSection,
    CopiedModelingReport,
    CorrelationSummary,
    DatasetColumnMetadata,
    DatasetComparisonResult,
    DatasetComparisonSampling,
    DatasetDriftDiagnostics,
    DatasetIssue,
    DatasetMetadata,
    DatasetOverview,
    DatasetPreview,
    DatasetProfile,
    DatasetQualityDiagnostics,
    DatasetSchemaDiff,
    DeletedModelingReport,
    DatetimeColumnProfile,
    DuckDBQueryResult,
    ExperimentPlanResult,
    FeatureSelectionResult,
    FrequencyInferenceResult,
    GroupTimeSeriesSummary,
    LeakageSummary,
    LeakageWarning,
    ModelingReadinessResult,
    ModelingReportCatalogSummary,
    ModelingReportMetadata,
    ModelingReportResult,
    ModelingReportSection,
    ModelingReportSectionMatch,
    ModelingReportSectionSummary,
    NullRateChange,
    NumericColumnProfile,
    NumericDrift,
    NumericHistogramBin,
    PreviewModelingReport,
    ProfileHeuristicSignal,
    ProfilingLimits,
    ReadModelingReport,
    ReadModelingReportSection,
    RenamedModelingReport,
    ReportSearchMatch,
    RowCountChange,
    SavedModelingReport,
    SavedModelingReportSection,
    SQLiteColumnInfo,
    SQLiteDatabaseInfo,
    SQLiteQueryResult,
    SQLiteTableSchema,
    StoredModelingReport,
    TargetSuggestionResult,
    TimestampRangeChange,
    TimeSeriesValidationResult,
    ValueFrequency,
    ValidationSplitMetadata,
]


def test_mcp_public_surface_snapshot() -> None:
    async def public_surface() -> tuple[list[str], list[str], list[str]]:
        server = create_mcp_server(Settings(mcp_transport="stdio"))
        resources = await server.list_resources()
        resource_templates = await server.list_resource_templates()
        tools = await server.list_tools()
        prompts = await server.list_prompts()
        resource_uris = sorted(str(resource.uri) for resource in resources)
        template_uris = sorted(str(template.uriTemplate) for template in resource_templates)
        tool_names = sorted(tool.name for tool in tools)
        prompt_names = sorted(prompt.name for prompt in prompts)
        return resource_uris + template_uris, tool_names, prompt_names

    resource_uris, tool_names, prompt_names = asyncio.run(public_surface())

    assert resource_uris == EXPECTED_RESOURCE_URIS
    assert tool_names == EXPECTED_TOOL_NAMES
    assert prompt_names == EXPECTED_PROMPT_NAMES


def test_cli_command_snapshot() -> None:
    assert _registered_cli_commands() == EXPECTED_CLI_COMMANDS


def test_result_model_field_snapshot() -> None:
    actual_fields = {
        model.__name__: list(model.model_fields)
        for model in sorted(RESULT_MODELS, key=lambda item: item.__name__)
    }

    assert actual_fields == EXPECTED_RESULT_MODEL_FIELDS


def _registered_cli_commands() -> list[str]:
    parser = build_parser()
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return sorted(action.choices)
    raise AssertionError("CLI parser does not define subcommands.")
