from __future__ import annotations

MAX_REPORT_PREVIEW_LINES = 12
MAX_REPORT_DIFF_PREVIEW_LINES = 40
MAX_REPORT_SEARCH_SNIPPET_LENGTH = 200
MAX_REPORT_SECTION_SNIPPET_LINES = 4
MAX_REPORT_SECTION_SUMMARY_EXAMPLES = 3
